#!/usr/bin/env python

from fboxaha import FritzAHA
import argparse
from datetime import datetime as dt
import sys

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('host', help='Hostname of the Fritz!Box')
parser.add_argument('--device', '-d', type=int, default=0, help='Device Number')
parser.add_argument('--list', '-l', action='store_true', help='List available devices')
parser.add_argument('--username', '-u', help='Username')
parser.add_argument('--password', '-p', help='Password')
parser.add_argument('--cert', '-c', help='SSL Certificate '
  'Fetch it with: '
  'openssl s_client -showcerts -connect your_fbox_hostname:443 < /dev/null | openssl x509 > fbox-cert.pem')

try:
    args = parser.parse_args()

    fb = FritzAHA(args.host, args.username, args.password, cert=args.cert)

    devices = fb.power_devices

    if args.list:
        for i in range(len(devices)):
            dev = devices[i]
            print('{0} : Device "#{1}" (connected state: {2}, power state: {3})'.format(i, *dev))
        sys.exit(0)

    sep = ';'
    if len(devices) > 0:
        while True:
            line = ''
            parts = [dt.now().strftime('%Y-%m-%dT%H:%M:%S')]
            parts += ['{:.2f}'.format(fb.get_last_consumption(devices[args.device][0]))]
            print(sep.join(parts))
except KeyboardInterrupt:
    pass

