#!/usr/bin/env python

from fboxaha import FritzAHA
import argparse
from datetime import datetime as dt
import sys

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('host', help='Hostname of the Fritz!Box')
parser.add_argument('--devices', '-d', type=int, nargs='*', default=[0], help='Device number (check available with --list)')
parser.add_argument('--list', '-l', action='store_true', help='List available devices')
parser.add_argument('--separator', '-s', default=' ', help='Output column separator')
parser.add_argument('--username', '-u', help='Username')
parser.add_argument('--password', '-p', help='Password')
parser.add_argument('--cert', '-c', help='SSL Certificate '
  'Fetch it with: '
  'openssl s_client -showcerts -connect your_fbox_hostname:443 < /dev/null | openssl x509 > fbox-cert.pem')

try:
    args = parser.parse_args()

    fb = FritzAHA(args.host, args.username, args.password, cert=args.cert)

    all_devices = fb.power_devices

    if args.list:
        for i in range(len(all_devices)):
            dev = all_devices[i]
            print('{0} : Device "#{1}" (connected state: {2}, power state: {3})'.format(i, *dev))
        sys.exit(0)

    for dev in args.devices:
        assert dev < len(all_devices)

    while True:
        line = ''
        parts = [dt.now().strftime('%Y-%m-%dT%H:%M:%S')]
        for dev in args.devices:
            parts.append('{:.2f}'.format(fb.get_last_consumption(all_devices[dev][0])))
        print(args.separator.join(parts))
except KeyboardInterrupt:
    pass

